export enum VIDEO_EVENTS {
  LOADSTART = 'loadstart',
  LOADEDDATA = 'loadeddata',
  LOADEDMETADATA = 'loadedmetadata',
  CANPLAY = 'canplay',
  CANPLAYTHROUGH = 'canplaythrough',
  PLAY = 'play',
  PAUSE = 'pause',
  ENDED = 'ended',
  TIMEUPDATE = 'timeupdate',
  PROGRESS = 'progress',
  SEEKED = 'seeked',
  ERROR = 'error',
  VOLUMECHANGE = 'volumechange',
  RATECHANGE = 'ratechange',
  DURATIONCHANGE = 'durationchange',
  ABORT = 'abort',
  SEEKING = 'seeking',
  STALLED = 'stalled',
  SUSPENDs = 'suspends',
  WAITING = 'waiting'
}
